@host = http://127.0.0.1:6000/v1/cats

GET {{host}}/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUyOTUwMTAzfQ.zJhoJ_onM1jGuEWvFIxiNeej9wQ8a2DKEFiWdvPulyc HTTP/1.1


###
POST {{host}}/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUyOTUwMTAzfQ.zJhoJ_onM1jGuEWvFIxiNeej9wQ8a2DKEFiWdvPulyc HTTP/1.1
Content-Type: application/json

[
    {
        "id": 1,
        "name": "Cathie2"
    },
    {
        "id":2,
        "name":"Catmandu2"
    },
    {
        "id":3,
        "name":"Catar2"
    }
]


###
PUT {{host}}/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUyOTUwMTAzfQ.zJhoJ_onM1jGuEWvFIxiNeej9wQ8a2DKEFiWdvPulyc HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "name": "CathieThe2nd"
}


###
DELETE {{host}}/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUyOTUwMTAzfQ.zJhoJ_onM1jGuEWvFIxiNeej9wQ8a2DKEFiWdvPulyc HTTP/1.1
Content-Type: application/json

[2,3]



###
GET {{host}}/1?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUyOTUwMTAzfQ.zJhoJ_onM1jGuEWvFIxiNeej9wQ8a2DKEFiWdvPulyc HTTP/1.1

###
PUT {{host}}/1?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUyOTUwMTAzfQ.zJhoJ_onM1jGuEWvFIxiNeej9wQ8a2DKEFiWdvPulyc HTTP/1.1
Content-Type: application/json

{
  "id": 3, 
  "name": "Catarsis"
}


###
DELETE {{host}}/1?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUyOTUwMTAzfQ.zJhoJ_onM1jGuEWvFIxiNeej9wQ8a2DKEFiWdvPulyc HTTP/1.1

###
GET {{host}}/?fields=name&offset=0&limit=5&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUyOTUwMTAzfQ.zJhoJ_onM1jGuEWvFIxiNeej9wQ8a2DKEFiWdvPulyc HTTP/1.1

###
GET {{host}}/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUyOTUwMTAzfQ.zJhoJ_onM1jGuEWvFIxiNeej9wQ8a2DKEFiWdvPulyc&fields=name HTTP/1.1